### PR TITLE
Support whitespace after comma in Identifiers

### PR DESCRIPTION
**Pull request by p0deje**
I'm not sure if that's correct or not, but it seems like IDL grammar allows using whitespace after comma in `Identifiers`.

It's actively used in the recent HTML5 spec:

```
[NoInterfaceObject, Exposed=(Window, Worker)]
interface NavigatorOnLine {
  readonly attribute boolean onLine;
};
```

This PR adds support for whitespace and also bumps IDL and HTML5 specs.

Also, Rake tasks use Nokogiri while it's not a part of development dependencies, so I added it too.

### CODE REVIEW

**Comment by jarib** [comment]
Looks fine to me. Do you want to take over this gem btw? I guess it's mostly used by Watir.

**Comment by jarib** [comment]
Released 0.2.0 with this patch.

**Comment by p0deje** [comment]
@jarib Thank you!

If you could just add me as contributor on Github and Rubygems, that would be great!

**Comment by p0deje** [comment]
Thank you for adding me to Github. Can you also add me as gem owner so that I could release?

**Comment by jarib** [comment]
Will do as soon as I'm in front of a shell

**Comment by jarib** [comment]
Done.

**Comment by p0deje** [comment]
Thank you, Jari!

**Pull request merged**
